### ISSUE TITLE
Feature request - wildcards

### ISSUE THREAD

**Issue by NFNChris** [wankdanker/node-object-mapper#20]
Thanks for the super-useful module.  I would love to see support for wildcards - at least at the beginning of expressions.  This would allow something like:

ListOrdersResponse.ListOrdersResult.Orders.Order[].ShippingAddress.AddressLine1

To become:

*.Order[].ShippingAddress.AddressLine1

It becomes especially useful for APIs that require one call for the initial page of results, and a slightly different call for subsequent pages.  Many of these APIs alter the envelope slightly for the "next page" results call so that you have to account for two mappings like:

ListOrdersResponse.ListOrdersResult

and

ListOrdersByNextTokenResponse.ListOrdersByNextTokenResult

Both of which actually have the same structure once you get to Orders.Order[].  Obviously not too hard to write a wrapper around, but would be great to see support within the module.

Thanks again!

**Comment by wankdanker** [comment]
Good idea. There are a bunch of glob libraries available which might make it easier to implement this. Next time I dig into this module I'll give it a shot. Otherwise, pull requests welcome from anyone. :)

**Comment by alemures** [comment]
Hi @wankdanker and @NFNChris , i just tried to implement glob patterns matching for object key values using minimatch module (ISC License). It looks promising and tests are passing successfully. I'll submit a pull request soon.

**Comment by alemures** [comment]
PR submitted: #47

**Comment by wankdanker** [comment]
@alemures I merged your pull request. And released object-mapper@5.0.0 to npm. Thank you for your contribution. If you get a chance, I'd take another pull request with updated documentation in the README.md. Thanks again!
