### ISSUE TITLE
Mapping source key properties with "."

### ISSUE THREAD

**Issue by jlulloav** [wankdanker/node-object-mapper#33]
Hi there,

I'm trying to accomplish this:

I have the following object. Please notice one of the key properties has a dot:
`{
  'item': {
       'account.id': 1,
  }
}`

The mapper object will be:
`{
    'item.account.id': 'id'
}`

I haven't found a way to accomplish this. Is there any way to do it with the mapper?

Thank you in advance.

**Comment by wankdanker** [comment]
@prinzdezibel's fix for this has been merged and released to npm as object-mapper@4.0.0
