### ISSUE TITLE
Handling non-existent sub-array elements of source object

### ISSUE THREAD

**Issue by nagarajanchinnasamy** [wankdanker/node-object-mapper#41]
For the following code:

    var om = require('object-mapper');

    var map = {
        "arr[].id": "arr[].id",
        "arr[].arr[].id": "arr[].arr[].id",
        "arr[].arr[].arr[].id": "arr[].arr[].arr[].id"
    };

    var src = {
        "arr": [
            {
                "id": 1
            }
        ]
    };

    var dest = om(src, map);
    console.log(JSON.stringify(dest));

as sub-array elements don't exist in `src`, the expected output would be:

    {"arr":[{"id":1}]}

However, the generated output is:

    {"arr":[{"id":1,"arr":[{"arr":[{}]}]}]}

I modified the code to fix this issue. Modifications do not break any of the tests :)

Will send a pull request. Please review. Thanks 👍

**Comment by switzer** [comment]
I've verified this as an issue and added your test.  I hope to fix shortly.

**Comment by switzer** [comment]
This is fixed in my branch
