### ISSUE TITLE
how to map an array

### ISSUE THREAD

**Issue by jackielihf** [wankdanker/node-object-mapper#5]
src: 
{
    "comments": [
    {"content": "aaa", "timestamp": "20150101" },
    {"content": "bbb", "timestamp": "20150102" }
]    
}

=>
dest:
{
 "comments": [
    {"newname": "aaa", "timestamp": "20150101" },
    {"newname": "bbb", "timestamp": "20150102" }
]  
}

**Comment by wankdanker** [comment]
@rafakato just added array mapping which can be found in v2.0.0, but it appears to not handle this based on this test case:

```js
var om = require("object-mapper");

var obj = {
  "comments" : [
    { a : 'aaa', b : 'bbbb'}
        , { a : 'aaa', b : 'bbbb'}
  ]
};

var map = {
  "comments[].a" : ["comments[].c"]
  , "comments[].b" : ["comments[].d"]
};

console.log(JSON.stringify(om(obj, {}, map)));

//{ comments: [ { c: null, d: null } ] }
```

I have always worked around this issue by having a separate map specifically for those comment objects and then looping through the array and calling object-mapper on each object and appending to my own new array.

It would be ideal to be able to have it properly mapped with object-mapper though.

**Comment by wankdanker** [comment]
Just pushed out v2.1.0 which should do what I described above.
