### ISSUE TITLE
should not generate empty Object when key has multiple level properties

### ISSUE THREAD

**Issue by NatasG** [wankdanker/node-object-mapper#57]
when we try to map
```
const src = {
}

const map = {
  "key1": "a.b.c"
}

ObjectMapper(src,map)
```

We expect a null object, but got 
```
{
  a: {
    b: {
    }
  }
}
```
Seems you just checked the latest level property like `c`, you still generate the `a.b`

**Comment by switzer** [comment]
Fixed this issue in my branch

**Comment by switzer** [comment]
I’m pushing code in the next day that fixes a couple of other issues from github FYI.
