### ISSUE TITLE
Performance Improve

### ISSUE THREAD

**Issue by rafakato** [wankdanker/node-object-mapper#8]
Hi,

I will use your module in a project that I need to have a great performance, so I was running some tests and the loops are not so great for the performance in large data.

I have some experience in developing using functional programming, can I try to implement your logic with this paradigm?

**Comment by rafakato** [comment]
Take a look at this: https://github.com/rafakato/node-object-mapper/blob/functional/index.js#L59

**Comment by wankdanker** [comment]
Hi @rafakato,

Please do. If you can increase performance and pass the tests then I would happily accept your changes.

Thanks,

Dan
