### ISSUE TITLE
Nullable value into an empty array

### ISSUE THREAD

**Issue by othke** [wankdanker/node-object-mapper#84]
Node: v12.16.2
version : 6.2.0

When I define a non nullable field on an empty array I get a 1 item array with a null value
```javascript
const src = {
  players: [],
};

const map = {
  "players[].name": "joueurs[].nom?",
};

const result = objectMapper(src, map);
```

Expected:
```javascript
{ joueurs: [ ] }
```

Result: 
```javascript
{ joueurs: [ { nom: null ] }
```

Any work around ?
Thanks

**Comment by abishek28007** [comment]
@othke Did you found any solution ?, facing the same issue

**Comment by othke** [comment]
@abishek28007  Unfortunately no :(

**Comment by abishek28007** [comment]
@othke Hey I just added `object-mapper.js `file in my code base and customised it.

**Comment by othke** [comment]
@abishek28007 Nice !
Can you show me where you add change ? I look into the source code but I don't see how to fix it.

**Comment by abishek28007** [comment]
instead of `return null` at line no: 63 I added `return []` in the function `getKeyValue()`

**Comment by othke** [comment]
That work for me also. But it break Some test :(
By the way this could be a quick fix. Thanks

**Comment by abishek28007** [comment]
@othke yeah thats why I moved the code to my own code base, need to debug the flow and then add condition to add empty array like null, I might use some special character for that.
